add_test( LineTest.TestsWork /home/arya/src/bfg/watch_build/bfg_test [==[--gtest_filter=LineTest.TestsWork]==] --gtest_also_run_disabled_tests)
set_tests_properties( LineTest.TestsWork PROPERTIES WORKING_DIRECTORY /home/arya/src/bfg/watch_build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RectangleTest.Width /home/arya/src/bfg/watch_build/bfg_test [==[--gtest_filter=RectangleTest.Width]==] --gtest_also_run_disabled_tests)
set_tests_properties( RectangleTest.Width PROPERTIES WORKING_DIRECTORY /home/arya/src/bfg/watch_build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RectangleTest.Height /home/arya/src/bfg/watch_build/bfg_test [==[--gtest_filter=RectangleTest.Height]==] --gtest_also_run_disabled_tests)
set_tests_properties( RectangleTest.Height PROPERTIES WORKING_DIRECTORY /home/arya/src/bfg/watch_build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RectangleTest.Centre /home/arya/src/bfg/watch_build/bfg_test [==[--gtest_filter=RectangleTest.Centre]==] --gtest_also_run_disabled_tests)
set_tests_properties( RectangleTest.Centre PROPERTIES WORKING_DIRECTORY /home/arya/src/bfg/watch_build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( bfg_test_TESTS LineTest.TestsWork RectangleTest.Width RectangleTest.Height RectangleTest.Centre)
