; `xyce` Sim Input for `__main__.Tb`
; Generated by `vlsirtools.XyceNetlister`
; 
; Anonymous `circuit.Package`
; Generated by `vlsirtools.XyceNetlister`
; 

.SUBCKT sky130_mux
+ S0 S0_B S1 S1_B S2 S2_B X0 X1 X2 X3 X4 X5 X6 X7 Y VPWR VGND 
; No parameters

xupper_left__fet0
+ upper_left__A0 S0_B X2 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xupper_left__fet1
+ upper_left__A1 S0_B X0 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xupper_left__fet2
+ X3 S0 upper_left__A0 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xupper_left__fet3
+ X1 S0 upper_left__A1 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xupper_left__fet4
+ A0 S1_B upper_left__A1 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xupper_left__fet5
+ upper_left__A0 S1 A0 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xlower_left__fet0
+ lower_left__A0 S0_B X6 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xlower_left__fet1
+ lower_left__A1 S0_B X4 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xlower_left__fet2
+ X7 S0 lower_left__A0 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xlower_left__fet3
+ X5 S0 lower_left__A1 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xlower_left__fet4
+ A1 S1_B lower_left__A1 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xlower_left__fet5
+ lower_left__A0 S1 A1 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xupper_right__fet0
+ upper_right__A0 S0 X2 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xupper_right__fet1
+ upper_right__A1 S0 X0 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xupper_right__fet2
+ X3 S0_B upper_right__A0 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xupper_right__fet3
+ X1 S0_B upper_right__A1 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xupper_right__fet4
+ A2 S1 upper_right__A1 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xupper_right__fet5
+ upper_right__A0 S1_B A2 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xlower_right__fet0
+ lower_right__A0 S0 X6 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xlower_right__fet1
+ lower_right__A1 S0 X4 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xlower_right__fet2
+ X7 S0_B lower_right__A0 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xlower_right__fet3
+ X5 S0_B lower_right__A1 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xlower_right__fet4
+ A3 S1 lower_right__A1 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xlower_right__fet5
+ lower_right__A0 S1_B A3 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xoutput_mux2__nfet0
+ Y S2_B A0 VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xoutput_mux2__nfet1
+ A1 S2 Y VGND 
+ sky130_fd_pr__nfet_01v8
+ PARAMS: w={480m} l={170m} 

xoutput_mux2__pfet0
+ Y S2 A2 VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

xoutput_mux2__pfet1
+ A3 S2_B Y VPWR 
+ sky130_fd_pr__pfet_01v8
+ PARAMS: w={640m} l={170m} 

.ENDS

.SUBCKT Tb
+ VSS 
; No parameters

xdut
+ s0 s0_b s1 s1_b s2 s2_b x0 x1 x2 x3 x4 x5 x6 x7 y dut_VPWR VSS 
+ sky130_mux
+ ; No parameters

vpower
+ dut_VPWR VSS 
+ dc {1.8} 
+ ac {0} 
+ ; No parameters

cfake_load
+ y VSS 
+ 2f
+ ; No parameters

vinit_x0
+ x0 VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

vinit_x1
+ x1 VSS 
+ dc {1.8} 
+ ac {0} 
+ ; No parameters

vinit_x2
+ x2 VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

vinit_x3
+ x3 VSS 
+ dc {1.8} 
+ ac {0} 
+ ; No parameters

vinit_x4
+ x4 VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

vinit_x5
+ x5 VSS 
+ dc {1.8} 
+ ac {0} 
+ ; No parameters

vinit_x6
+ x6 VSS 
+ dc {0} 
+ ac {0} 
+ ; No parameters

vinit_x7
+ x7 VSS 
+ dc {1.8} 
+ ac {0} 
+ ; No parameters

vs0_driver
+ s0 VSS 
+ pulse ({0} {1.8} {50p} {50p} {50p} {500p} {1n}) 
+ ; No parameters

vs0_b_driver
+ s0_b VSS 
+ pulse ({1.8} {0} {50p} {50p} {50p} {500p} {1n}) 
+ ; No parameters

vs1_driver
+ s1 VSS 
+ pulse ({0} {1.8} {50p} {50p} {50p} {1n} {2n}) 
+ ; No parameters

vs1_b_driver
+ s1_b VSS 
+ pulse ({1.8} {0} {50p} {50p} {50p} {1n} {2n}) 
+ ; No parameters

vs2_driver
+ s2 VSS 
+ pulse ({0} {1.8} {50p} {50p} {50p} {2n} {4n}) 
+ ; No parameters

vs2_b_driver
+ s2_b VSS 
+ pulse ({1.8} {0} {50p} {50p} {50p} {2n} {4n}) 
+ ; No parameters

.ENDS

xtop 0 Tb ; Top-Level DUT 

.lib /home/arya/src/pdk-root/share/pdk/sky130A/libs.tech/ngspice/sky130.lib.spice tt
.tran 1e-12 4e-09 

.print tran format=csv v(*) i(*) 

.end 

