syntax = "proto3";

package bfg.proto.parameters;

message InterconnectWireBlock {
  enum RoutingTrackDirection {
    TRACK_HORIZONTAL = 0;
    TRACK_VERTICAL = 1;
  }

  enum LayoutMode {
    CONSERVATIVE = 0;
    MODESTLY_CLEVER = 1;
  }

  message Break {
    // Default side (false) or the other one (span of off-axis).
    optional bool alternate_side = 1;

    // Offset along main axis.
    optional int64 offset = 2;
  }

  message Bundle {
    optional int32 num_wires = 1;

    // If true, the wires in this bundle are broken out (or in) with orthogonal
    // wires running to the parallel edge of the block. If false, the wires in
    // the bundle are drawn straight through from the start of the block to the
    // end.
    optional bool tap = 2;

    // If tap is true and break_out is specified, the starting wires in the
    // block are drawn and broken out according to the details in the Break
    // message. If tap is true and break_out is missing, the starting wires are
    // not drawn.
    optional Break break_out = 3;

    // If tap is true and break_in is specified, the ending wires in the block
    // are drawn and broken out according to the details in the Break message.
    // If tap is true and break_in is missing, the ending wires are not drawn.
    optional Break break_in = 4;
  }

  message Channel {
    optional string name = 1;

    // 2, 3, 4 reserved for the old break_out, num_bundles, bundle fields.
    reserved 2, 3, 4;

    repeated Bundle bundles = 5;
  }

  optional RoutingTrackDirection direction = 1;
  optional LayoutMode layout_mode = 2;

  optional string horizontal_layer = 4;
  optional string via_layer = 5;
  optional string vertical_layer = 6;

  optional int64 horizontal_wire_width_nm = 7;
  optional int64 horizontal_wire_pitch_nm = 8;
  optional int64 horizontal_wire_offset_nm = 9;
  optional int64 vertical_wire_width_nm = 10;
  optional int64 vertical_wire_pitch_nm = 11;
  optional int64 vertical_wire_offset_nm = 12;

  optional uint64 length = 13;

  repeated Channel channels = 14;

  optional int64 first_break_out_start_nm = 15;
  optional int64 second_break_out_start_nm = 16;
}
